import { Ubuntu } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";

const ubuntu_font = Ubuntu({
  variable: "--font-geist-sans",
  weight: ['300', '400', '500', '700'],
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={ubuntu_font.className}>
          <ConvexClientProvider>

            
            {children}
          </ConvexClientProvider>
            
        </body>
      </html>
    </>
  )
}



